import "./globals.css";
import { IBM_Plex_Sans } from "next/font/google";

const inter = IBM_Plex_Sans({ weight: ["100", "300", "400", "700"], subsets: ["latin-ext"] });

export const metadata = {
	title: "Prices Podlasiak",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${inter.className}`}>{children}</body>
		</html>
	);
}
