import "./globals.css";
import { Roboto } from "next/font/google";

const inter = Roboto({ weight: ["100", "300", "400", "500", "700"], subsets: ["latin-ext"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
