export const config = {
  type: {
    catalog: "feed/generate/catalog",
    ceneo: "feed/generate/ceneo",
    merchant: "feed/generate/merchant",
  },
  source: [
    { source: "rea", lang: "pl", url: "https://lazienka-rea.com.pl/" },
    { source: "rea", lang: "uk", url: "https://bathroom-rea.co.uk/" },
    { source: "rea", lang: "de", url: "https://badezimmer-rea.de/" },
    { source: "rea", lang: "cz", url: "https://koupelna-rea.cz/" },
    { source: "rea", lang: "fr", url: "https://salledebain-rea.fr/" },
    { source: "rea", lang: "lt", url: "https://vonioskambarys-rea.lt/" },
    { source: "rea", lang: "ro", url: "https://baie-rea.ro/" },
    { source: "rea", lang: "sk", url: "https://kupelna-rea.sk/" },
    { source: "rea", lang: "hu", url: "https://furdoszoba-rea.hu/" },
    { source: "rea", lang: "it", url: "https://bagno-rea.it/" },
    { source: "rea", lang: "bg", url: "https://bania-rea.bg/" },
    { source: "rea", lang: "ua", url: "https://rea.ua/" },
    { source: "rea", lang: "es", url: "https://bano-rea.es/" },
    { source: "rea", lang: "ee", url: "https://vannituba-rea.ee/" },
    { source: "rea", lang: "hr", url: "https://kupaona-rea.hr/" },
    { source: "rea", lang: "lv", url: "https://vannasistaba-rea.lv/" },
    { source: "rea", lang: "nl", url: "https://badkamer-rea.nl/" },
    { source: "rea", lang: "me", url: "https://kupaona-rea.me/" },
    { source: "rea", lang: "rs", url: "https://kupaona-rea.rs/" },
    { source: "rea", lang: "be", url: "https://salledebain-rea.be/" },
    { source: "rea", lang: "at", url: "https://badezimmer-rea.at/" },
    { source: "rea", lang: "ie", url: "https://bathroom-rea.ie/" },
    { source: "rea", lang: "si", url: "https://kopalnica-rea.si/" },
    { source: "tutumi", lang: "pl", url: "https://tutumi.pl/" },
    { source: "tutumi", lang: "uk", url: "https://en.tutumi.pl/" },
    { source: "tutumi", lang: "de", url: "https://de.tutumi.pl/" },
    { source: "tutumi", lang: "cz", url: "https://cz.tutumi.pl/" },
    { source: "tutumi", lang: "fr", url: "https://fr.tutumi.pl/" },
    { source: "tutumi", lang: "lt", url: "https://lt.tutumi.pl/" },
    { source: "tutumi", lang: "ro", url: "https://ro.tutumi.pl/" },
    { source: "tutumi", lang: "sk", url: "https://sk.tutumi.pl/" },
    { source: "tutumi", lang: "hu", url: "https://hu.tutumi.pl/" },
    { source: "tutumi", lang: "it", url: "https://it.tutumi.pl/" },
    { source: "tutumi", lang: "bg", url: "https://bg.tutumi.pl/" },
    { source: "tutumi", lang: "ua", url: "https://ua.tutumi.pl/" },
    { source: "tutumi", lang: "es", url: "https://es.tutumi.pl/" },
    { source: "toolight", lang: "pl", url: "https://toolight.pl/" },
    { source: "toolight", lang: "uk", url: "https://toolight.co.uk/" },
    { source: "toolight", lang: "de", url: "https://toolight.de/" },
    { source: "toolight", lang: "fr", url: "https://toolight.fr/" },
    { source: "toolight", lang: "lt", url: "https://toolight.lt/" },
    { source: "toolight", lang: "ro", url: "https://toolight.ro/" },
    { source: "toolight", lang: "hu", url: "https://toolight.hu/" },
    { source: "toolight", lang: "it", url: "https://toolight.it/" },
    { source: "toolight", lang: "bg", url: "https://toolight.bg/" },
    { source: "toolight", lang: "es", url: "https://toolight.es/" },
    { source: "toolight", lang: "ee", url: "https://toolight.ee/" },
    { source: "toolight", lang: "hr", url: "https://toolight.hr/" },
    { source: "toolight", lang: "lv", url: "https://toolight.lv/" },
    { source: "toolight", lang: "nl", url: "https://toolight.nl/" },
    { source: "toolight", lang: "me", url: "https://toolight.me/" },
    { source: "toolight", lang: "rs", url: "https://toolight.rs/" },
    { source: "toolight", lang: "at", url: "https://toolight.at/" },
    { source: "toolight", lang: "si", url: "https://toolight.si/" },
  ],
  mailing: {
    subject: "Price Change Podlasiak",
    clients: [
      { email: "drteski@gmail.com", lang: "pl" },
      { email: "teski666@gmail.com", lang: "de" },
    ],
  },
};
