export const config = {
  type: {
    catalog: "feed/generate/catalog",
    ceneo: "feed/generate/ceneo",
    merchant: "feed/generate/merchant",
  },
  source: {
    rea: {
      pl: "https://lazienka-rea.com.pl/",
      uk: "https://bathroom-rea.co.uk/",
      de: "https://badezimmer-rea.de/",
      cz: "https://koupelna-rea.cz/",
      fr: "https://salledebain-rea.fr/",
      lt: "https://vonioskambarys-rea.lt/",
      ro: "https://baie-rea.ro/",
      sk: "https://kupelna-rea.sk/",
      hu: "https://furdoszoba-rea.hu/",
      it: "https://bagno-rea.it/",
      bg: "https://bania-rea.bg/",
      ua: "https://rea.ua/",
      es: "https://bano-rea.es/",
      ee: "https://vannituba-rea.ee/",
      hr: "https://kupaona-rea.hr/",
      lv: "https://vannasistaba-rea.lv/",
      nl: "https://badkamer-rea.nl/",
      me: "https://kupaona-rea.me/",
      rs: "https://kupaona-rea.rs/",
      be: "https://salledebain-rea.be/",
      at: "https://badezimmer-rea.at/",
      ie: "https://bathroom-rea.ie/",
      si: "https://kopalnica-rea.si/",
    },
    tutumi: {
      pl: "https://tutumi.pl/",
      uk: "https://en.tutumi.pl/",
      de: "https://de.tutumi.pl/",
      cz: "https://cz.tutumi.pl/",
      fr: "https://fr.tutumi.pl/",
      lt: "https://lt.tutumi.pl/",
      ro: "https://ro.tutumi.pl/",
      sk: "https://sk.tutumi.pl/",
      hu: "https://hu.tutumi.pl/",
      it: "https://it.tutumi.pl/",
      bg: "https://bg.tutumi.pl/",
      ua: "https://ua.tutumi.pl/",
      es: "https://es.tutumi.pl/",
    },
    toolight: {
      pl: "https://toolight.pl/",
      uk: "https://toolight.co.uk/",
      de: "https://toolight.de/",
      fr: "https://toolight.fr/",
      lt: "https://toolight.lt/",
      ro: "https://toolight.ro/",
      hu: "https://toolight.hu/",
      it: "https://toolight.it/",
      bg: "https://toolight.bg/",
      es: "https://toolight.es/",
      ee: "https://toolight.ee/",
      hr: "https://toolight.hr/",
      lv: "https://toolight.lv/",
      nl: "https://toolight.nl/",
      me: "https://toolight.me/",
      rs: "https://toolight.rs/",
      at: "https://toolight.at/",
      si: "https://toolight.si/",
    },
  },
};
